[project]
name = "edu-mcp-telegram"
version = "0.1.0"
description = "Educational MCP Telegram Bot with FastMCP"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.9.2",
    "python-telegram-bot>=22.1",
    "requests>=2.31.0",
]
